feat: Add an optional feature to set the keyring directory function
deepin-community/gnome-keyring pull request #1
Opened 2023-08-02 08:33 UTC by chenchongbiao

增加一个可选使用的特性，设置keyring目录功能，该特性不影响流程
    
Log: Add an optional feature

2023-08-02 08:38 UTC, UTsweetyfish requested changes
没更新 d/changelog

2023-08-02 09:03 UTC, hudeng-go commented
unrelease的版本号，不会在github添加tag呀

2023-08-02 09:12 UTC, chenchongbiao commented
> unrelease的版本号，不会在github添加tag呀

ok 修改成stable可以不。

2023-08-02 09:24 UTC, UTsweetyfish requested changes
这个 patch 建议暂缓合并

1. 这个 patch 与其中的 `GNOME_KEYRING_CUSTOM_LOCAL_PATH` 环境变量不是外部的，是公司内部 gerrit 的，与白盒项目有关
2. 以环境变量的方式做逻辑是否很怪？
3. 可维护性存疑？

2023-08-10 07:49 UTC, chenchongbiao commented
linuxdeepin/developer-center/issues/3572

2023-08-10 07:53 UTC, chenchongbiao commented
/integrate

2023-08-11 08:56 UTC, chenchongbiao commented
默认不启用，可不合入，先做记录。

2023-08-11 08:56 UTC, closed without merging